Feature: Added traffic, Bugfix: configfile parsing
Signed-off-by: bjanssens <bjanssens@inuits.eu>

diff --git a/5pm_again b/5pm_again
--- a/5pm_again
+++ b/5pm_again
@@ -15,6 +15,7 @@ Options:
     --start | -s     : Don't use last to get the login time but the current time
     --version | -v   : Get the version
     --snappy | -sn   : Get a snappy comment back
+    --traffic        : Show the current traffic situation
 
   Configuration based on a daily fasion can be done in the /home/$whoami/.5pm/config file.
   Here one can add days where there are specific options. This is done in the following format:
@@ -34,18 +35,9 @@ debug () {
   fi
 }
 
-# Configparams
-configparams () {
-  # Params needed for config
-  username=$( whoami )
-  # Directories and files
-  currentdir="/home/${username}/.5pm"
-  configfile="${currentdir}/config"
-  # Check if users .5pm directory exists
-  if [ ! -d $currentdir ]; then
-    debug Creating "$currentdir" directory
-    mkdir $currentdir
-  fi
+error () {
+  echo "Error: $@"
+  exit 1
 }
 
 # Params
@@ -58,23 +50,29 @@ params () {
   if [ -z $starts ]; then starts=false; fi
   if [ -z $version ]; then version=false; fi
   if [ -z $snappy ]; then snappy=false; fi
+  if [ -z $traffic ]; then traffic=false; fi
+  if [ -z $routes ]; then routes=''; fi
   # Needed for script
   installdir=$( dirname "${BASH_SOURCE[0]}" )
-  # Time stamps
-  dateYmd=$( date +%Y%m%d )
-  currentH=$( date +%H )
-  currentM=$( date +%M )
-  workhoursH=$( echo $workhours | cut -d ':' -f1 )
-  workhoursM=$( echo $workhours | cut -d ':' -f2 )
-  regexHHMM='^[0-2]{0,1}[0-9]{1}\:[0-9]{2}$'
+  trafficcliscript='/home/bjanssens/Inuits/Scripts/Trafficcli/get_traffic_cli'
+  # Params needed for config
+  username=$( whoami )
+  # Directories and files
+  currentdir="/home/${username}/.5pm"
+  configfile="${currentdir}/config"
+  # Check if users .5pm directory exists
+  if [ ! -d $currentdir ]; then
+    debug Creating "$currentdir" directory
+    mkdir $currentdir
+  fi
   # Tempfile
   tempfile="${currentdir}/.${dateYmd}.tmp"
   # Param checking
+  regexHHMM='^[0-2]{0,1}[0-9]{1}\:[0-9]{2}$'
   if [ ! -z $workhours ]; then
     if [[ ! $workhours =~ $regexHHMM ]]; then
-      echo 'Error: Workhours did not match the expected format, please use "hh:mm"'
-      echo "Error: Regex that is used to match agains: $regexHHMM"
-      exit 1
+      error Workhours did not match the expected format, please use "hh:mm"
+      error Regex that is used to match agains: $regexHHMM
     fi
   fi
 }
@@ -84,27 +82,19 @@ config () {
   if [ -f "$configfile" ]; then
     #   %a   locale's abbreviated weekday name (e.g., Sun)
     currentD=$( date +%a )
-    for config in $( cat $configfile | sed 's/ /_/g' )
+    for config in $( cat $configfile | sed 's/ /+/g' )
     do
-      configwunder=$( echo $config | sed 's/_/ /g' )
-      regexConfig='(Mon|Tue|Wed|Thu|Fri)\=((\s{0,1}(--workhours|-w)\=\"[0-2]{0,1}[0-9]{1}\:[0-9]{2}\")|\s(-m)){0,5}'
-      if [[ ! $configwunder =~ $regexConfig ]]
-      then
-        echo "Error: Configuration syntax issue on line: \` $configwunder \`"
-        #exit 1
-      fi
+      configwunder=$( echo $config | sed 's/+/ /g' )
+      #regexConfig='^(Mon|Tue|Wed|Thu|Fri)\=((\s{0,1}(--workhours|-w)\=\"[0-2]{0,1}[0-9]{1}\:[0-9]{2}\")|\s(--routes\s*)|\s(-m)){0,5}$'
+      #if [[ ! $configwunder =~ $regexConfig ]]
+      #then
+      #  error Configuration syntax issue on line: \` $configwunder \`
+      #fi
       day=$( echo $config | cut -d '=' -f 1 )
       if [[ "${day}" == "$currentD" ]]
       then
-        configOpts=$( echo $config | sed "s/$day=//g" | sed 's/_/ /g' )
-        for optionfull in $configOpts
-        do
-          optionkey=$( echo $optionfull | cut -d '=' -f 1 )
-          if [ "${optionkey}" == "--workhours" ]; then
-            optionvalue=$( echo $optionfull | cut -d '=' -f 2 )
-            workhours=$( echo $optionvalue | sed 's/"//g' )
-          fi
-        done
+        configOpts=$( echo $config | sed "s/$day=//g" | sed 's/+/ /g' )
+        parse_options $configOpts
       fi
     done
   else
@@ -127,6 +117,16 @@ parse_nice () {
     M=$( echo "0${M}" )
   fi
   echo "${H}:${M}"
+}
+
+# Set times
+cal_times () {
+  # Time stamps
+  dateYmd=$( date +%Y%m%d )
+  currentH=$( date +%H )
+  currentM=$( date +%M )
+  workhoursH=$( echo $workhours | cut -d ':' -f1 | sed "s/'//g" )
+  workhoursM=$( echo $workhours | cut -d ':' -f2 | sed "s/'//g" )
 }
 
 # Get the uptime
@@ -201,6 +201,10 @@ nice_print () {
   then
     snappy $leaveS
   fi
+  if $traffic
+  then
+    get_traffictime
+  fi
 }
 
 # Make some snappy remark based upon $remaining
@@ -253,51 +257,73 @@ snappy () {
   fi
 }
 
-configparams
-config
+get_traffictime () {
+  if [ ! -f $trafficcliscript ]
+  then
+    error get_traffic_cli script not found
+    exit 1
+  else
+    $trafficcliscript -r "$routes"
+  fi
+}
 
-while test -n "$1"
-do
-  case "$1" in
-    --help|-h)
-      showhelp
-      ;;
-    --start|-s)
-      starts=true
-      shift
-      ;;
-    --debug|-d)
-      debug=true
-      shift
-      ;;
-    --more|-m)
-      more=true
-      shift
-      ;;
-    --quiet|-q)
-      quiet=true
-      shift
-      ;;
-    --workhours|-w)
-      shift
-      workhours=$1
-      shift
-      ;;
-    --snappy|-sn)
-      snappy=true
-      shift
-      ;;
-    --version|-v)
-      version=true
-      shift
-      ;;
-    *)
-      showhelp
-      ;;
-  esac
-done
+parse_options () {
+  while test -n "$1"
+  do
+    case "$1" in
+      --help|-h)
+        showhelp
+        ;;
+      --start|-s)
+        starts=true
+        shift
+        ;;
+      --debug|-d)
+        debug=true
+        shift
+        ;;
+      --more|-m)
+        more=true
+        shift
+        ;;
+      --quiet|-q)
+        quiet=true
+        shift
+        ;;
+      --workhours|-w)
+        shift
+        workhours=$1
+        shift
+        ;;
+      --route|-r)
+        shift
+        routes="$routes $1"
+        shift
+        ;;
+      --snappy|-sn)
+        snappy=true
+        shift
+        ;;
+      --version|-v)
+        version=true
+        shift
+        ;;
+      --traffic)
+        traffic=true
+        shift
+        ;;
+      *)
+        showhelp
+        ;;
+    esac
+  done
+}
 
 params
+config
+parse_options $@
+
+cal_times
 if $version; then
   get_version
 fi
